countries_list = ['France','Spanish','Italy','England','USA']
print(countries_list)
print(sorted(countries_list))
print(countries_list)
print(sorted(countries_list, reverse=True))
print(countries_list)
countries_list.reverse()
print(countries_list)
countries_list.reverse()
print(countries_list)
countries_list.sort()
print(countries_list)
countries_list.sort(reverse=True)
print(countries_list)