products_list = ['Avacado', 'Cashew', 'Carrot', 'Onion', 'Celery', 'Milk', 'Cucumber']
print(products_list)
print(f"\n\tI not have {products_list[0].title()}.")
products_list[0] = 'Bred'
print(f"\n\tBut i have {products_list[0].title()}.")
print(products_list)
products_list.append('Avacado')
print(f"\n\tNo i have {products_list[-1].title()}.")
print(products_list)
products_list.insert(3, 'Batter')
print(f"\n\tBrought the {products_list[3].title()} to the warehouse!")
print(products_list)
print(f"\n\tThe warehouse is out of {products_list[6]}!")
del products_list[6]
print(products_list)
not_have_product = products_list.pop()
print(f"\n\t The warehouse is out {not_have_product.title()}.")
print(products_list)
products_list.remove('Bred')
print(products_list)
not_have_product = 'Carrot'
products_list.remove(not_have_product)
print(products_list)
products_list.sort()
print(products_list)
products_list.sort(reverse=True)
print(products_list)
print(sorted(products_list))
print(products_list)
print(len(products_list ))
