# Generated by Django 5.2.3 on 2025-06-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_s', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizzas',
            new_name='Pizza',
        ),
    ]
