# Generated by Django 5.2.3 on 2025-06-29 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_s', '0002_rename_pizzas_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_s.pizza')),
            ],
            options={
                'verbose_name_plural': 'toppings',
            },
        ),
    ]
