invitation_list = ['Teador','Kris','Nikc']
print(f"Invitation to dinner for {invitation_list[0].title()}.")
print(f"Invitation to dinner for {invitation_list[1].title()}.")
print(f"Invitation to dinner for {invitation_list[2].title()}.")
print(f"{invitation_list[0].title()} can't come to dinner.")
invitation_list[0] = 'Melissa'
print(invitation_list)
print(f"Invitation to dinner for {invitation_list[0].title()}.")
print(f"Invitation to dinner for {invitation_list[1].title()}.")
print(f"Invitation to dinner for {invitation_list[2].title()}.")
print("More places available!")
invitation_list.insert(0, 'George')
invitation_list.insert(3, 'Luisa')
invitation_list.append('Ben')
print(invitation_list)
print(len(invitation_list))
print(f"Invitation to dinner for {invitation_list[0].title()}.")
print(f"Invitation to dinner for {invitation_list[1].title()}.")
print(f"Invitation to dinner for {invitation_list[2].title()}.")
print(f"Invitation to dinner for {invitation_list[3].title()}.")
print(f"Invitation to dinner for {invitation_list[4].title()}.")
print(f"Invitation to dinner for {invitation_list[5].title()}.")
print("There are only 2 seats for dinner.")
cancel_invite = invitation_list.pop(0)
print(f"Our regrets {cancel_invite.title()}!")
print(invitation_list)
cancel_invite = invitation_list.pop(0)
print(f"Our regrets {cancel_invite.title()}!")
print(invitation_list)
cancel_invite = invitation_list.pop(0)
print(f"Our regrets {cancel_invite.title()}!")
print(invitation_list)
cancel_invite = invitation_list.pop(0)
print(f"Our regrets {cancel_invite.title()}!")
print(invitation_list)
print(f"We are waiting for you {invitation_list[0].title()}!")
print(f"We are waiting for you {invitation_list[1].title()}!")
del invitation_list[0]
del invitation_list[0]
print(invitation_list)
